### PR TITLE
Check if MX is catchall or not

### PR DESCRIPTION
**Pull request by malayladu**
This pull request will fix issue #1

### CODE REVIEW

**Comment by malayladu** [comment]
@yunjunseokzb  Kindly, review this pull request and merge it.

**Comment by malayladu** [comment]
@yunjunseokzb  Thanks!

Hope, this will be available through NPM soon.

**Comment by yunjunseokzb** [comment]
NPM publish done and catchall test is now optional.
Thank you!!

**Comment by malayladu** [comment]
Awesome 👍

**Pull request merged**
